/* prettier-ignore */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as DashboardImport } from "./routes/_dashboard"
import { Route as DashboardDlqImport } from "./routes/_dashboard/dlq"
import { Route as DashboardFlowsIdImport } from "./routes/_dashboard/flows/$id"
import { Route as DashboardFlowsIndexImport } from "./routes/_dashboard/flows/index"
import { Route as DashboardIndexImport } from "./routes/_dashboard/index"
import { Route as DashboardJobsIdImport } from "./routes/_dashboard/jobs/$id"
import { Route as DashboardJobsIndexImport } from "./routes/_dashboard/jobs/index"
import { Route as LoginImport } from "./routes/login"

// Create Virtual Routes

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: "/_dashboard",
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardDlqRoute = DashboardDlqImport.update({
  id: "/dlq",
  path: "/dlq",
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardJobsIndexRoute = DashboardJobsIndexImport.update({
  id: "/jobs/",
  path: "/jobs/",
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardFlowsIndexRoute = DashboardFlowsIndexImport.update({
  id: "/flows/",
  path: "/flows/",
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardJobsIdRoute = DashboardJobsIdImport.update({
  id: "/jobs/$id",
  path: "/jobs/$id",
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardFlowsIdRoute = DashboardFlowsIdImport.update({
  id: "/flows/$id",
  path: "/flows/$id",
  getParentRoute: () => DashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_dashboard": {
      id: "/_dashboard"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    "/_dashboard/": {
      id: "/_dashboard/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
    "/_dashboard/dlq": {
      id: "/_dashboard/dlq"
      path: "/dlq"
      fullPath: "/dlq"
      preLoaderRoute: typeof DashboardDlqImport
      parentRoute: typeof DashboardImport
    }
    "/_dashboard/jobs/": {
      id: "/_dashboard/jobs/"
      path: "/jobs"
      fullPath: "/jobs"
      preLoaderRoute: typeof DashboardJobsIndexImport
      parentRoute: typeof DashboardImport
    }
    "/_dashboard/flows/": {
      id: "/_dashboard/flows/"
      path: "/flows"
      fullPath: "/flows"
      preLoaderRoute: typeof DashboardFlowsIndexImport
      parentRoute: typeof DashboardImport
    }
    "/_dashboard/jobs/$id": {
      id: "/_dashboard/jobs/$id"
      path: "/jobs/$id"
      fullPath: "/jobs/$id"
      preLoaderRoute: typeof DashboardJobsIdImport
      parentRoute: typeof DashboardImport
    }
    "/_dashboard/flows/$id": {
      id: "/_dashboard/flows/$id"
      path: "/flows/$id"
      fullPath: "/flows/$id"
      preLoaderRoute: typeof DashboardFlowsIdImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof DashboardIndexRoute
  "/login": typeof LoginRoute
  "/dlq": typeof DashboardDlqRoute
  "/jobs": typeof DashboardJobsIndexRoute
  "/flows": typeof DashboardFlowsIndexRoute
  "/jobs/$id": typeof DashboardJobsIdRoute
  "/flows/$id": typeof DashboardFlowsIdRoute
}

export interface FileRoutesByTo {
  "/": typeof DashboardIndexRoute
  "/login": typeof LoginRoute
  "/dlq": typeof DashboardDlqRoute
  "/jobs": typeof DashboardJobsIndexRoute
  "/flows": typeof DashboardFlowsIndexRoute
  "/jobs/$id": typeof DashboardJobsIdRoute
  "/flows/$id": typeof DashboardFlowsIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/_dashboard": typeof DashboardRoute
  "/login": typeof LoginRoute
  "/_dashboard/": typeof DashboardIndexRoute
  "/_dashboard/dlq": typeof DashboardDlqRoute
  "/_dashboard/jobs/": typeof DashboardJobsIndexRoute
  "/_dashboard/flows/": typeof DashboardFlowsIndexRoute
  "/_dashboard/jobs/$id": typeof DashboardJobsIdRoute
  "/_dashboard/flows/$id": typeof DashboardFlowsIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/dlq"
    | "/jobs"
    | "/flows"
    | "/jobs/$id"
    | "/flows/$id"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/login" | "/dlq" | "/jobs" | "/flows" | "/jobs/$id" | "/flows/$id"
  id:
    | "__root__"
    | "/_dashboard"
    | "/login"
    | "/_dashboard/"
    | "/_dashboard/dlq"
    | "/_dashboard/jobs/"
    | "/_dashboard/flows/"
    | "/_dashboard/jobs/$id"
    | "/_dashboard/flows/$id"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const DashboardRouteChildren = {
  DashboardIndexRoute,
  DashboardDlqRoute,
  DashboardJobsIndexRoute,
  DashboardFlowsIndexRoute,
  DashboardJobsIdRoute,
  DashboardFlowsIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren
)

export const routeTree = rootRoute
  ._addFileChildren({
    DashboardRoute: DashboardRouteWithChildren,
    LoginRoute,
  })
  ._addFileTypes<FileRouteTypes>()
