name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main", "changesets/release"]
  merge_group:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number to run CI for"
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read
  pull-requests: read
  checks: write
  statuses: write

# You can leverage Vercel Remote Caching with Turbo to speed up your builds
# @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
env:
  FORCE_COLOR: 3

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/setup

      - name: Generate prisma client
        run: pnpm -F adapter-prisma prisma:generate

      - name: Lint
        run: pnpm lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/setup

      - name: Format
        run: pnpm format

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/setup

      - name: Generate prisma client
        run: pnpm -F adapter-prisma prisma:generate

      - name: Typecheck
        run: pnpm typecheck
