name: Deploy docs

on:
  pull_request:
    types:
      - closed
    branches:
      - "changeset-release/main"
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main')

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/setup

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        
      - name: Deploy to Production
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          
      - name: Deploy to Preview
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: vercel --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
